# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: boxafe 0.1.9 ruby lib

Gem::Specification.new do |s|
  s.name = "boxafe"
  s.version = "0.1.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["AlphaHydrae"]
  s.date = "2017-02-07"
  s.description = "Boxafe encrypts and auto-mounts a folder with encfs and whenever."
  s.email = "hydrae.alpha@gmail.com"
  s.executables = ["boxafe"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "bin/boxafe",
    "lib/boxafe.rb",
    "lib/boxafe/box.rb",
    "lib/boxafe/cli.rb",
    "lib/boxafe/config.rb",
    "lib/boxafe/encfs.rb",
    "lib/boxafe/program.rb",
    "lib/boxafe/validator.rb"
  ]
  s.homepage = "http://github.com/AlphaHydrae/boxafe"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Secure your Dropbox with encfs."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<paint>, ["~> 1.0"])
      s.add_runtime_dependency(%q<commander>, ["~> 4.2"])
      s.add_runtime_dependency(%q<which_works>, ["~> 1.0"])
      s.add_runtime_dependency(%q<dotenv>, ["~> 2.1"])
      s.add_runtime_dependency(%q<mutaconf>, ["~> 0.2.0"])
      s.add_runtime_dependency(%q<notifies>, ["~> 0.1.0"])
      s.add_runtime_dependency(%q<multi_scheduler>, ["~> 0.1.2"])
      s.add_development_dependency(%q<rake>, ["~> 11.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rake-version>, ["~> 1.0"])
      s.add_development_dependency(%q<fakefs>, ["~> 0.10.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.12.0"])
      s.add_development_dependency(%q<coveralls>, ["~> 0.8.16"])
    else
      s.add_dependency(%q<paint>, ["~> 1.0"])
      s.add_dependency(%q<commander>, ["~> 4.2"])
      s.add_dependency(%q<which_works>, ["~> 1.0"])
      s.add_dependency(%q<dotenv>, ["~> 2.1"])
      s.add_dependency(%q<mutaconf>, ["~> 0.2.0"])
      s.add_dependency(%q<notifies>, ["~> 0.1.0"])
      s.add_dependency(%q<multi_scheduler>, ["~> 0.1.2"])
      s.add_dependency(%q<rake>, ["~> 11.3"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rake-version>, ["~> 1.0"])
      s.add_dependency(%q<fakefs>, ["~> 0.10.0"])
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<simplecov>, ["~> 0.12.0"])
      s.add_dependency(%q<coveralls>, ["~> 0.8.16"])
    end
  else
    s.add_dependency(%q<paint>, ["~> 1.0"])
    s.add_dependency(%q<commander>, ["~> 4.2"])
    s.add_dependency(%q<which_works>, ["~> 1.0"])
    s.add_dependency(%q<dotenv>, ["~> 2.1"])
    s.add_dependency(%q<mutaconf>, ["~> 0.2.0"])
    s.add_dependency(%q<notifies>, ["~> 0.1.0"])
    s.add_dependency(%q<multi_scheduler>, ["~> 0.1.2"])
    s.add_dependency(%q<rake>, ["~> 11.3"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rake-version>, ["~> 1.0"])
    s.add_dependency(%q<fakefs>, ["~> 0.10.0"])
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<simplecov>, ["~> 0.12.0"])
    s.add_dependency(%q<coveralls>, ["~> 0.8.16"])
  end
end

